<a href="https://colab.research.google.com/github/shravanipidurkar/shravani-google-colab/blob/main/Numpy_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array1=np.array([[11,12,13],[14,15,16],[17,18,19]])
array1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
import numpy as np
array2=np.array([[5,6,7],[1,2,3],[10,11,12]])
array2

array([[ 5,  6,  7],
       [ 1,  2,  3],
       [10, 11, 12]])

In [ ]:
#Addition
re_array=array1+array2
print("\nBy Operator Method:\n",re_array)
re_array=np.add(array1,array2)
print("By numpy")


By Operator Method:
 [[16 18 20]
 [15 17 19]
 [27 29 31]]
By numpy


In [ ]:
#Subtraction
re_array=array1-array2
print("\nBy Operator Method:\n",re_array)
re_array=np.subtract(array1,array2)
print("By numpy")


By Operator Method:
 [[ 6  6  6]
 [13 13 13]
 [ 7  7  7]]
By numpy


In [ ]:
#Multiplication
re_array=array1*array2
print("\nBy Operator Method:\n",re_array)
re_array=np.multiply(array1,array2)
print("By numpy")


By Operator Method:
 [[ 55  72  91]
 [ 14  30  48]
 [170 198 228]]
By numpy


In [ ]:
#Division1/2
re_array=array1/array2
print("\nBy Operator Method:\n",re_array)
re_array=np.divide(array1,array2)
print("By numpy")


By Operator Method:
 [[ 2.2         2.          1.85714286]
 [14.          7.5         5.33333333]
 [ 1.7         1.63636364  1.58333333]]
By numpy


In [ ]:
#Mod
re_array=array1%array2
print("\nBy Operator Method:\n",re_array)
re_array=np.mod(array1,array2)
print("By numpy")


By Operator Method:
 [[1 0 6]
 [0 1 1]
 [7 7 7]]
By numpy


In [ ]:
#Division2/1
re_array=array2/array1
print("\nBy Operator Method:\n",re_array)
re_array=np.divide(array2,array1)
print("By numpy")


By Operator Method:
 [[0.45454545 0.5        0.53846154]
 [0.07142857 0.13333333 0.1875    ]
 [0.58823529 0.61111111 0.63157895]]
By numpy


numpy documentayion from which we can get information is  :
numpy.org & geeksforgeeks.org

In [ ]:
#Dot product
re_array=np.dot(array1,array2)
print(re_array)

[[197 233 269]
 [245 290 335]
 [293 347 401]]


In [ ]:
re_array=np.transpose(array1)
print(re_array)


re_array=np.transpose(array2)
print(re_array)

[[11 14 17]
 [12 15 18]
 [13 16 19]]
[[ 5  1 10]
 [ 6  2 11]
 [ 7  3 12]]


In [ ]:
#Horizontal stacking
re_array=np.hstack((array1,array2))
print(re_array)

[[11 12 13  5  6  7]
 [14 15 16  1  2  3]
 [17 18 19 10 11 12]]


In [ ]:
#Vertical stacking
re_array=np.vstack((array1,array2))
print(re_array)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [ 5  6  7]
 [ 1  2  3]
 [10 11 12]]


In [ ]:
import numpy as np
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
 #Shape
 import numpy as np
 arr=np.array([[1,2,3,4],[5,6,7,8]])
 print(arr.shape)

(2, 4)
